### PR TITLE
Issue 475 profile page not working

### PR DESCRIPTION
**Pull request by anilnatha**
Here is what is contained in this pull request:

1. Updated environment specific paths in `maapprofile.php`
2. Fixed setting of request method in `maapprofile.php` when fetching User profile.
3. Added deployment notes to README, including how to create the plugin ZIP file.
4. Merged in a change that was found in DIT, but not saved in the repo.

### CODE REVIEW

**Comment by bsatoriu** [comment]
@anilnatha everything is working correctly except for the public SSH key upload. I tried uploading a new SSH key after logging into https://dit.maap-project.org/profile/ but the file was not saved.

**Comment by anilnatha** [comment]
Thanks for reviewing this.  I'll take a look at the SSH key upload issue and report back.

**Comment by anilnatha** [comment]
Hey @bsatoriu I've committed the final changes we spoke of earlier today that resolve the issue with the proxy granting ticket.  These changes are rolled out on DIT and functional. Once you have had an opportunity to review this, I'll push out the changes to UAT for Sri to review.

**Comment by bsatoriu** [comment]
Thanks @anilnatha, looks good.

**Review by bsatoriu — APPROVED** [review]

**Comment by anilnatha** [comment]
@bsatoriu Thank you.  I'll push this out to UAT tomorrow.

**Pull request merged**
